### PR TITLE
feat: use host/user/pass from env vars #406

### PR DESCRIPTION
**Pull request by mahnunchik**
Feature description: https://github.com/flyte/mqtt-io/issues/406

* It is not a breaking change
* Config parsing kept as is
* Config validation kept as is
* Environment variables has precedence over config

I think it is simplest way to bring this feature to mqtt-io

### CODE REVIEW

**Comment by mahnunchik** [comment]
@flyte @mschlenstedt @BenjiU may I ask for the review of this PR?

**Comment by BenjiU** [comment]
ah damn! I typed this last week, but didn't sent it :-/

That looks nice! One improvement would be, to just have the PW via ENV and the other configs from the file, but that can be improved later.

Would you please document this configuration (in the readme)?

**Comment by mahnunchik** [comment]
> One improvement would be, to just have the PW via ENV and the other configs from the file, but that can be improved later.

All variables have default from the config file, so it is possible to specify only necessary env vars to override specific config variables.

My goal was to be able to specify all the variables ​as env vars ​that the mosquito writes to the automatic discovery "registry" https://github.com/home-assistant/addons/blob/d5f529465229c3075ae3306769e1378d9b507028/mosquitto/rootfs/etc/services.d/mosquitto/discovery#L18-L50

**Comment by mahnunchik** [comment]
@BenjiU I've opened another PR about readme updates haha 😆  https://github.com/flyte/mqtt-io/pull/405

But I can document it manually

**Comment by BenjiU** [comment]
Ah, your right, of course! Perfect!

yeah, just a short manual documentation, so someone knows it is there. then i will merge and release it.

Thanks for your contribution and i'll have a look at #405

**Comment by mahnunchik** [comment]
@BenjiU documentation has been added

**Review by BenjiU — APPROVED** [review]

**Pull request merged**
