### PR TITLE
added: air quality to bme680 sensor

### PR DESCRIPTION
**Pull request by crssnd**
I exposed the gas and air_quality for the BME680 sensor, and also added an config example.

### CODE REVIEW

**Comment by mschlenstedt** [comment]
Good suggestion!

But you made maybe more changes then needed (e. g. logging). Maybe you should remove these things (maybe there are left from your tests?).

This would clean up your PR and makes it more readable (and checkable).

**Comment by crssnd** [comment]
> Good suggestion!
> 
> But you made maybe more changes then needed (e. g. logging). Maybe you should remove these things (maybe there are left from your tests?).
> 
> This would clean up your PR and makes it more readable (and checkable).

removed the logging part

**Comment by crssnd** [comment]
anything else that you think should be changed?

**Comment by crssnd** [comment]
no feedback from the maintainers

**Comment by mschlenstedt** [comment]
I think it is worse to wait until somebody has time to review the PR. Developement is unfortunately not very active anymore...

@BenjiU @flyte ? Maybe you can check and include the PR? Air Quality is the main reason for this sensor... So it should be included.

**Comment by JackGlobetrotter** [comment]
@crssnd Thanks for your work, really appreciate it! I have tried your implementation, it seems to introduce quit a lot of noise into temperature and humidity readings during gas measurement (which is possibly due to heating of bme680). I made some little changes to avoid these readings during gas measurement. Will open an new PR if that is fine for you ?

**Pull request closed without merging**
