### PR TITLE
Add support for adafruit ads1x15 anlog digital converter

### PR DESCRIPTION
**Pull request by r00tat**
I've added a new sensor_module for the [ads1x15](https://learn.adafruit.com/adafruit-4-channel-adc-breakouts/python-circuitpython) analog digital converter based on the [Adafruit CircuitPython lib](https://github.com/adafruit/Adafruit_CircuitPython_ADS1x15).

### CODE REVIEW

**Comment by flyte** [comment]
Awesome, looks good! Thanks :grin:

**Comment by flyte** [comment]
Thanks for sorting out the pylint issues too. I'm aware that they're a little strict.

**Comment by r00tat** [comment]
What's the correct auto formatting for this project? I'm using yapf, but if I save `server.py` it messes up with your code. What tooling and what config should be used for this project?

**Comment by flyte** [comment]
I should make some contributing guidelines shouldn't I?

I use black for formatting. Line length of 90 if I recall correctly, but I
may be wrong. I'll check once I'm back at my PC.

I also use pylint and mypy for static analysis, you can run them both with
tox or "make lint".

**Comment by r00tat** [comment]
Yeah some contributing guidelines would be great! A starting point can be a simple how to develop or something like this. 

I really appreciate your work as it works great and is easy extensible.

**Pull request merged**
