### PR TITLE
Add Feature/optional display name for homeassistant discovery + some more stuff for home assistant

### PR DESCRIPTION
**Pull request by rlehfeld**
I started off of https://github.com/flyte/pi-mqtt-gpio/pull/152

Further, the scheme tests for python 2.7 does not work for me. Not sure how to fix this. I disabled it for the moment.
1. Documents activation of HomeAssistant MQTT discovery
2. Adds the option to set a human readable name per input/output pin, or sensor. This allows for example to use spaces and german umlauts.
3. Adds the option to change the component used for the discovery
4. Adds the option to define the device_class for digital_inputs.

### CODE REVIEW

**Comment by flyte** [comment]
Hi @rlehfeld ! Thanks for your work. It all makes complete sense and I'm happy to include it.

However, I'm sorry to waste your time, but I'm afraid I won't merge this PR. I'm not continuing development work on the current version of the software, as I've done a huge rebuild using asyncio on `feature/asyncio` (#178).

If you were to submit a new PR to make the same changes on `feature/asyncio` then I'd gladly merge that one. One change I'd prefer though, is to prefix the config options with `ha_`, so `component` becomes `ha_component` etc. to differentiate them from config options that change the behaviour of this software.

If you don't want to make the changes on the new version then I'll probably migrate the changes myself at some point, but I don't want to just close your PR and steal all the credit!

Cheers :beers:

**Comment by rlehfeld** [comment]
@flyte I was somehow expecting this and also the prefix makes sense for me.
I will see what I can do.

**Comment by flyte** [comment]
Having said all that, I just saw #171 which makes me think that I'd actually prefer to put all of the HA discovery config into its own dict, which would allow us to add config schema for only the most important parts, and allow extra values that we can tack on to the discovery payload to be added as well.

For example:

```yaml
digital_inputs:
  - name: doorbell
    module: whatever
    ha_discovery:
      component: binary_sensor
      device_class: button
      display_name: Ding Dong
      charging_topic: what/ever/topic
```

Then have the schema something like this:

```yaml
digital_inputs:
  type: list
  required: no
  default: []
  schema:
    type: dict
    allow_unknown: yes
    schema:
      name:
        type: string
        required: yes
        empty: no
      ... etc
      ha_discovery:
        type: dict
        allow_unknown: yes
        schema:
          component:
            type: string
            required: no
            default: binary_sensor
```

Make sense?

**Comment by rlehfeld** [comment]
@flyte it makes absolutely sense. I also came across the need the add the `force_update` flag and was thinking the same. I would have done exactly that now that you "closed" my request.

**Pull request closed without merging**
