### PR TITLE
Initial implementation of serial stream

### PR DESCRIPTION
**Pull request by ChrisEAlfred**
Initial PR for streams serial port implementation

### CODE REVIEW

**Comment by BenjiU** [comment]
Hi ChrisEAlfred, I changed the import sequence, so module is only required, if it is mentioned in config.yml.
And my smartmeter talks "hex", so I added a encoding value. If it is set, the serial read data is encoded for proper sending via mqtt.
May you test, if it is still working for your project?
Thank you

**Comment by flyte** [comment]
Just wanted to say that this is a really nice idea, and thanks for submitting the PR, @ChrisEAlfred ! I'll hang on until you've tested out the changes made by @BenjiU before merging.

**Comment by ChrisEAlfred** [comment]
I have tested @BenjiU changes and all is fine by me.
I commented out the debug messages as they can be verbose.

**Comment by BenjiU** [comment]
Hey, I changed the printfs to _LOG system traces, because I like traces, that can be switched on by the user without touching source code :-)
@flyte: may be merged, if you don't see anything.

**Comment by flyte** [comment]
Cool, thanks guys! I'll add it to the growing list of things to test out before the next release!

**Pull request merged**
