### PR TITLE
New sensor HC-SR04 (very cheap ultrasonic distance sensor)

### PR DESCRIPTION
**Pull request by a-tom-s**
Please commit my new changes for the HC-SR04 ultrasonic sensor to the base repository.
Thanks, Tom

### CODE REVIEW

**Comment by flyte** [comment]
Hey @a-tom-s thanks for the PR!

I'm curious to know how this interacts with the `raspberrypi` GPIO module, since it uses that and runs its own setup (setting pin mode, and potentially using the same pins). Have you tested it with the `raspberrypi` module configured at the same time?

**Comment by a-tom-s** [comment]
Hi Ellis,

I tested it with one additional digital input and it worked fine. I'll test it with digital output(s) as soon as possible.

Your project is really great, congratulations  and many thanks for your work. I found it while I was searching fora solution to connect my Raspi with IO and ultrasonic sensors (to measure water level of rain water tanks) to my home automation. Most of my home automation is ESP8266 based, but for several ultrasonic sensors and control of several valves and pumps, the Raspi is the better solution.

regards

Thomas


Am 04.03.20 um 17:27 schrieb Ellis Percival:

Hey @a-tom-s<https://github.com/a-tom-s> thanks for the PR!

I'm curious to know how this interacts with the raspberrypi GPIO module, since it uses that and runs its own setup (setting pin mode, and potentially using the same pins). Have you tested it with the raspberrypi module configured at the same time?

**Comment by BenjiU** [comment]
Hey @a-tom-s, have you tested with the output pins already?

**Comment by a-tom-s** [comment]
Yes, I did and it worked fine. I checked it with one input and one output.RegardsTomAm 10.05.2020 18:50 schrieb Benji <notifications@github.com>:
Hey @a-tom-s, have you tested with the output pins already?

**Comment by flyte** [comment]
Thank you! Sorry it took so long to merge.

**Pull request merged**
