### PR TITLE
Set the client ID to the device hostname.

### PR DESCRIPTION
**Pull request by mrinc**
I had some issues with missing client ID's so I just set it to default to what ever the hostname of the device is.

### CODE REVIEW

**Comment by flyte** [comment]
Hey, thanks for the PR!

I'm a little worried that this will affect people who have multiple Pis on their network with the same hostname (the Raspbian default). I'd like to extend this to be a config value, perhaps defaulting to the local hostname, but with a random string appended so the defaults don't interfere with other instances.

What do you think?

**Comment by mrinc** [comment]
Hey,

Fair enough, currently there is no id at all, so if there are multiple pi's with the same hostnames, it would be exactly the same anyway?

We could use the hostname + the last digit of the IP so there would be no chance of a duplicate?

Thanks

**Comment by flyte** [comment]
Currently, the client ID will be randomly generated each time the software is run: https://www.eclipse.org/paho/clients/python/docs/#id1

> We could use the hostname + the last digit of the IP so there would be no chance of a duplicate?

There's still a chance of a duplicate, for example, two devices, one on 10.0.0.10 and one on 10.0.1.10. 

I think I'd prefer to stick to a totally randomised client ID (as it is now) as a default and just add the option of setting it to something in the config file. Are there any reasons you know of to prefer making part of the default client ID static and part randomised, as opposed to fully randomised?

There's a bit more information in the code here: https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/client.py#L460

**Comment by flyte** [comment]
I also propose that if the config value is set to a specific client ID, then we set `clean_session` to False.

**Comment by mrinc** [comment]
Aha! 

I think an optimal solution would then be to check if there is an ID set and not blank, else force the generation of the ID.

So the worst case is safe rather than blank like I had.

Comments?

**Comment by flyte** [comment]
If you don't specify a client ID then, depending on the protocol in use, the `paho-mqtt` library or the server will generate a client ID for you - it doesn't need any forcing to do that.

What was the issue you were having exactly?

**Comment by mrinc** [comment]
By default the ID was blank (as defined in your code), which yes it should have been generated but didn't.

From a quick search again: https://pypi.python.org/pypi/paho-mqtt/1.1#constructor-reinitialise
`the unique client id string used when connecting to the broker. If client_id is zero length or None, then one will be randomly generated. In this case the clean_session parameter must be True.`  

But most specifically this part: ` In this case the clean_session parameter must be True.`  
Which it's not defined as true and that is why I think it's not getting a generated id.  

However, **clean_session**: boolean that determines the client type. If True, the broker will remove all information about this client when it disconnects. If False, the client is a durable client and subscription information and queued messages will be retained when the client disconnects.
Note that a client will never discard its own outgoing messages on disconnect. Calling connect() or reconnect() will cause the messages to be resent. Use reinitialise() to reset a client to its original state.`

I don't think we should be setting this to `true` at all and we should generate the id on our side.

**Comment by flyte** [comment]
> I don't think we should be setting this to true at all and we should generate the id on our side.

Agreed. Check out https://github.com/flyte/pi-mqtt-gpio/commit/19eedb4335a4e11281d27159c29516fcb43b3c2e and see if that's in line with what you're thinking.

PS. Sorry, been busy since we last spoke.

**Comment by mrinc** [comment]
I like that idea, then multiple services can be run on a single device with different ids.

**Comment by flyte** [comment]
Thanks for your input @mrinc! I've "merged" the PR but actually just used the commit I mentioned previously. Hope that works for you.

**Pull request merged**
