### PR TITLE
Update ads1x15.py

### PR DESCRIPTION
**Pull request by maxthebuch**
Avoids race condition when reading a channel

### CODE REVIEW

**Comment by skvsn** [comment]
I'm using ads1115 on my RPI4 and if I configure more that one channel - mqtt-io seems to crash after some time. When running with only one channel - everything works perfectly. So hopefully this will fix this problem. Another way of achieving this could be by setting max_workers=1 on this module's ThreadPoolExecutor object

**Review by maxthebuch — COMMENTED** [review]
Formatting with LINT

**Comment by skvsn** [comment]
I tested this version with all 4 channels enabled - it is running fine for more than day now and not crashing as before. Would be great if this fix could be included in the main branch of mqtt-io

**Comment by mschlenstedt** [comment]
@flyte Happy New Year ;-)

Any time to include this PR and make a new version? Would be great, since this is really an important Bugfix when using an ads1x15

**Pull request merged**
