### PR TITLE
migrate mcp3008 from adafruit to gpiozero

### PR DESCRIPTION
**Pull request by gueux**
As the adafruit libraries are deprecated [Adafruit_GPIO](https://github.com/adafruit/Adafruit_Python_GPIO)/[Adafruit_MCP3008 ](https://github.com/adafruit/Adafruit_Python_MCP3008) i propose the cheapest variant of migration to native [gpiozero](https://github.com/gpiozero/gpiozero) MCP3008 implementation

### CODE REVIEW

**Comment by flyte** [comment]
Hi @gueux !

Thanks for the PR, but we're [not accepting PRs into the current stable version any more](https://github.com/flyte/pi-mqtt-gpio#-new-asynchronous-version-in-beta-).

Sorry to waste your time, but would you mind checking out `feature/asyncio` and making the changes to that branch instead?

Cheers!

**Comment by gueux** [comment]
@flyte I don't see `feature/asyncio` branch anymore. Could you point me to current branch I can create merge request for?

**Comment by flyte** [comment]
Ah yes, it's merged now, so develop is the right place.

**Comment by gueux** [comment]
@flyte thx. i will create the new one.

**Pull request closed without merging**
