### PR TITLE
interrupt_payload_reset

### PR DESCRIPTION
**Pull request by a-x-**
For example, HomeAssistant motion sensor should send clear signal (OFF) after motion one (ON)

Looks like it’s alike `timed_set_ms` but w/o delay.
Maybe, I should reimplement it to make this config similar

### CODE REVIEW

**Comment by a-x-** [comment]
I don’t understand what cause build fail

**Comment by BenjiU** [comment]
I also bot this to my last PR. Maybe they upgraded Python? @flyte has to look at it, i think.

**Comment by a-x-** [comment]
Mm, I got: I need to update https://github.com/flyte/pi-mqtt-gpio/blob/develop/config.schema.yml

**Comment by a-x-** [comment]
hm, still failing...
```
/usr/bin/make black
231make[1]: Entering directory '/home/travis/build/flyte/pi-mqtt-gpio'
232black -l 90 pi_mqtt_gpio
233make[1]: black: Command not found
234Makefile:6: recipe for target 'black' failed
235make[1]: *** [black] Error 127
236make[1]: Leaving directory '/home/travis/build/flyte/pi-mqtt-gpio'
237Makefile:2: recipe for target 'schema' failed
```

**Comment by a-x-** [comment]
Can anyone help with CI?

**Comment by a-x-** [comment]
I checked now, 
It works!

I installed it via pip right from github

**Comment by a-x-** [comment]
Oh, It worked...........
I so need this patch

**Comment by a-x-** [comment]
Hm, no CI now?

**Comment by flyte** [comment]
I've been thinking about this issue a bit, and I'm not sure that I like the solution to this problem. It doesn't really make sense to me to send two messages per interrupt, as the second message doesn't actually relate to any event that's happened (like the pin changed value) in real life.

> I so need this patch

You might find that the asyncio version that I'm working on in `feature/asyncio` will help you here. I've recently added some brand new interrupt logic that will publish real pin values instead of just one value on every interrupt whether it's rising or falling.

Hopefully you'll be able to get it working, but send me a message on discord if you get stuck.

> Hm, no CI now?

Yeah, don't worry about that for the moment.

**Comment by flyte** [comment]
I'm closing this PR for the reasons above, but let's have any further interrupt-based discussions here https://github.com/flyte/pi-mqtt-gpio/discussions/179 .

I may be open to allowing interrupts to be configured this way, but I'd need a bit of convincing that it couldn't be solved any other way first.

**Pull request closed without merging**
