### PR TITLE
md: add necessary dependency

### PR DESCRIPTION
**Pull request by a-x-**
I spent 10 minutes to found true library...

### CODE REVIEW

**Comment by flyte** [comment]
Hey @a-x- could you explain a bit about what problem this solves? Perhaps my memory is failing me, but isn't this installed automatically from pip when you're using the Raspberry Pi GPIO module?

**Comment by a-x-** [comment]
Your forgot critical dependency
It even not obvious from error stack trace what the problem

I spent 10 minutes to found true library...

If I it add to requirement.txt, will it installed automatically in the future?

**Comment by flyte** [comment]
This is only a critical dependency when you use the Raspberry Pi's GPIO. If you don't run this on a Raspberry Pi then you probably don't need it.

That's why these dependencies are installed at run time depending which modules you enable in your config file.

If you give us the logs that are output when you try to run, and your config file, then hopefully it'll help us to work out what your problem is.

**Comment by flyte** [comment]
I'm going to close this for now, since I think it's a misunderstanding of the module requirements installation system. If I've made a mistake, or you want to show the logs that demonstrate your issue, please feel free to comment.

**Pull request closed without merging**
